language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - travis_retry composer install

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - composer require satooshi/php-coveralls:dev-master
  - php vendor/bin/coveralls -v
